--- #YAML:1.0
name: Email-FolderType
version: 0.6
license: perl
distribution_type: module
requires:
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Email::FolderType:
    file: lib/Email/FolderType.pm
    version: 0.6
generated_by: Module::Build version 0.20
